#!/usr/bin/env python3
"""Search for a lossless 16-run Spacefiller observation code.

Each candidate run observes eight adjacent Level 2 cells.  A cell is encoded
as 0 (dead), 1 (live with the first row parity), or 2 (live with the second
row parity).  Adjacent live cells must use the same parity.  The signature
tables were exhaustively generated by ``reverse_spacefiller.py``.

The search is counterexample guided:

* Z3 finds two legal 64-cell strings with different binary values that the
  currently selected runs cannot distinguish.
* A minimum hitting-set model chooses observations that distinguish every
  counterexample seen so far.
* The process stops only when Z3 proves that no collision remains.

The parity model is deliberately conservative.  It permits either parity for
every one-run rather than relying on CPython's secret-seeded PRNG, so an UNSAT
result proves the binary decoder for every parity assignment the level can
produce.
"""

from __future__ import annotations

import argparse
import json
import time
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import z3


ROOT = Path(__file__).resolve().parents[2]
TABLE_TEMPLATE = ROOT / "analysis/level2/spacefiller2-signatures{suffix}.json"
OUTPUT_PATH = ROOT / "analysis/level2/spacefiller2-observation-code.json"
SECRET_BITS = 64
CONTEXT_BITS = 8


@dataclass(frozen=True, order=True)
class Test:
    start: int
    phase: int


def geometry_code(symbols: tuple[int, ...]) -> int:
    return sum(symbol * (3**index) for index, symbol in enumerate(symbols))


def load_signature_maps() -> list[dict[int, int]]:
    result: list[dict[int, int]] = []
    for phase in range(5):
        suffix = "" if phase == 0 else f"-dy{phase}"
        payload = json.loads(
            Path(str(TABLE_TEMPLATE).format(suffix=suffix)).read_text(
                encoding="utf-8"
            )
        )
        signatures = sorted({record["signature"] for record in payload["records"]})
        signature_ids = {signature: index for index, signature in enumerate(signatures)}
        result.append(
            {
                geometry_code(tuple(map(int, record["geometry"]))): signature_ids[
                    record["signature"]
                ]
                for record in payload["records"]
            }
        )
    return result


def candidate_tests() -> tuple[Test, ...]:
    # Keep one observation in each four-bit slot.  Allowing a one-cell shift
    # either way is enough to move every hidden edge symbol into an observable
    # interior position, while the slot structure prevents large unobserved
    # gaps that would make both the decoder and the proof needlessly large.
    return tuple(
        Test(start, phase)
        for slot in range(16)
        for start in range(-3 + 4 * slot, 4 * slot)
        for phase in range(5)
    )


def local_code(values: tuple[int, ...], start: int) -> int:
    return sum(
        (values[bit] if 0 <= bit < SECRET_BITS else 0) * (3**offset)
        for offset, bit in enumerate(range(start, start + CONTEXT_BITS))
    )


class CollisionVerifier:
    def __init__(
        self,
        tests: tuple[Test, ...],
        signature_maps: list[dict[int, int]],
    ) -> None:
        self.tests = tests
        self.signature_maps = signature_maps

    def collision(
        self, selected: set[int]
    ) -> tuple[tuple[int, ...], tuple[int, ...]] | None:
        chosen = [self.tests[index] for index in sorted(selected)]
        phases_by_end: dict[int, list[int]] = defaultdict(list)
        for test in chosen:
            phases_by_end[test.start + CONTEXT_BITS - 1].append(test.phase)
        first_position = min(test.start for test in chosen)
        last_position = max(test.start + CONTEXT_BITS - 1 for test in chosen)

        # State key: the two trailing seven-symbol base-3 codes, plus whether
        # their binary contents have differed anywhere.  The value retains one
        # complete base-3 witness for reconstruction if a collision survives.
        states: dict[tuple[int, int, bool], tuple[int, int]] = {
            (0, 0, False): (0, 0)
        }
        trailing_length = 0
        power7 = 3**7
        for position in range(first_position, last_position + 1):
            allowed = (0,) if position < 0 or position >= SECRET_BITS else (0, 1, 2)
            next_states: dict[tuple[int, int, bool], tuple[int, int]] = {}
            if trailing_length:
                previous_divisor = 3 ** (trailing_length - 1)
            else:
                previous_divisor = 1
            for (code_a, code_b, different), (full_a, full_b) in states.items():
                previous_a = (code_a // previous_divisor) % 3
                previous_b = (code_b // previous_divisor) % 3
                for symbol_a in allowed:
                    if previous_a and symbol_a and previous_a != symbol_a:
                        continue
                    window_a = code_a + symbol_a * (
                        3**trailing_length if trailing_length < 7 else power7
                    )
                    for symbol_b in allowed:
                        if previous_b and symbol_b and previous_b != symbol_b:
                            continue
                        window_b = code_b + symbol_b * (
                            3**trailing_length if trailing_length < 7 else power7
                        )
                        if trailing_length >= 7 and any(
                            self.signature_maps[phase][window_a]
                            != self.signature_maps[phase][window_b]
                            for phase in phases_by_end.get(position, ())
                        ):
                            continue
                        trailing_a = window_a if trailing_length < 7 else window_a // 3
                        trailing_b = window_b if trailing_length < 7 else window_b // 3
                        binary_differs = (
                            0 <= position < SECRET_BITS
                            and bool(symbol_a) != bool(symbol_b)
                        )
                        key = (
                            trailing_a,
                            trailing_b,
                            different or binary_differs,
                        )
                        if key in next_states:
                            continue
                        next_full_a = full_a
                        next_full_b = full_b
                        if 0 <= position < SECRET_BITS:
                            next_full_a += symbol_a * (3**position)
                            next_full_b += symbol_b * (3**position)
                        next_states[key] = (next_full_a, next_full_b)
            states = next_states
            trailing_length = min(7, trailing_length + 1)

        witness = next(
            (full for state, full in states.items() if state[2]),
            None,
        )
        if witness is None:
            return None

        def decode(value: int) -> tuple[int, ...]:
            return tuple((value // (3**index)) % 3 for index in range(SECRET_BITS))

        return decode(witness[0]), decode(witness[1])


class HittingSet:
    def __init__(
        self,
        tests: tuple[Test, ...],
        limit: int,
    ) -> None:
        self.tests = tests
        self.flags = tuple(z3.Bool(f"pick_{index}") for index in range(len(tests)))
        self.solver = z3.Solver()
        if limit != 16:
            raise ValueError("the slotted search currently requires 16 runs")
        for slot in range(16):
            choices = [
                self.flags[index]
                for index, test in enumerate(tests)
                if -3 + 4 * slot <= test.start < 4 * slot
            ]
            self.solver.add(z3.PbEq([(choice, 1) for choice in choices], 1))

    def add_counterexample(self, separating: list[int]) -> None:
        if not separating:
            raise RuntimeError("no candidate observation separates a collision")
        self.solver.add(z3.Or(*(self.flags[index] for index in separating)))

    def solve(self) -> set[int] | None:
        if self.solver.check() != z3.sat:
            return None
        model = self.solver.model()
        return {
            index
            for index, flag in enumerate(self.flags)
            if z3.is_true(model.eval(flag, model_completion=True))
        }


def separating_tests(
    collision: tuple[tuple[int, ...], tuple[int, ...]],
    tests: tuple[Test, ...],
    signature_maps: list[dict[int, int]],
) -> list[int]:
    a, b = collision
    result = []
    for index, test in enumerate(tests):
        code_a = local_code(a, test.start)
        code_b = local_code(b, test.start)
        if signature_maps[test.phase][code_a] != signature_maps[test.phase][code_b]:
            result.append(index)
    return result


def binary_value(symbols: tuple[int, ...]) -> int:
    return sum((symbol != 0) << index for index, symbol in enumerate(symbols))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=16)
    parser.add_argument("--max-rounds", type=int, default=1000)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()

    maps = load_signature_maps()
    tests = candidate_tests()
    verifier = CollisionVerifier(tests, maps)
    selected = {
        index
        for index, test in enumerate(tests)
        if test.phase == 0 and test.start in range(-2, 59, 4)
    }
    if len(selected) != args.limit:
        raise RuntimeError("the seeded observation code expects a 16-run limit")
    hitting_set = HittingSet(tests, args.limit)

    for round_index in range(1, args.max_rounds + 1):
        collision = verifier.collision(selected)
        if collision is None:
            chosen = [tests[index] for index in sorted(selected)]
            payload = {
                "format": "golduck-spacefiller2-observation-code",
                "version": 1,
                "run_limit": args.limit,
                "proof_model": "all legal one-run parity assignments",
                "runs": [
                    {"context_start": test.start, "probe_dy": test.phase}
                    for test in chosen
                ],
            }
            args.output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
            print(f"UNSAT: {len(chosen)} observations uniquely determine all 64 bits")
            print(f"wrote {args.output}")
            return 0

        separating = separating_tests(collision, tests, maps)
        hitting_set.add_counterexample(separating)
        replacement = hitting_set.solve()
        if replacement is None:
            print(f"more than {args.limit} observations required after round {round_index}")
            return 1
        selected = replacement
        if round_index <= 10 or round_index % 10 == 0:
            a, b = collision
            print(
                f"round {round_index}: collision "
                f"0x{binary_value(a):016x}/0x{binary_value(b):016x}; "
                f"{len(separating)} separating candidates; selected={len(selected)}",
                flush=True,
            )

    print(f"no proof after {args.max_rounds} rounds")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
